manifest:
  defaults:
    revision: v0.3
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: fishjord
      url-base: https://gitea.chrono.zone/fishjord
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-module
      remote: fishjord
      revision: main
  self:
    path: config
